### ISSUE TITLE
I am a bit confused as to why this is not working on my pc...

### ISSUE THREAD

**Issue by C3R3S1** [dwjclark11/TextRPG#3]
I am trying to learn a bit more about making a game in c++ and have been loving the tutorials but I have run into issues and I am not sure how to go about fixing it. I would appreciate some help to get it working. I have gotten to #5-2 in the series and now when I run it I get the wrong output.
![image](https://github.com/user-attachments/assets/33e1f9ee-4c2e-46e8-a008-fa02a5596ddd)

**Comment by dwjclark11** [comment]
@C3R3S1 Hello, this has to do with the console size. If you slowly drag the width of the console smaller/bigger, does it ever align correctly? I may have added a fix for this in the master.

**Comment by dwjclark11** [comment]
@C3R3S1 I believe that this commit 0eac3ab may fix the issue above.

**Comment by C3R3S1** [comment]
Yeah when I resize it it does fix it! I had tried that a little but I think I just missed when it finally worked... And the new commit works as well. Thank you for your help and for making such a great series of videos for people to learn from!

**Comment by dwjclark11** [comment]
@C3R3S1 You're welcome!
