### ISSUE TITLE
Bug in ItemMenuState.cpp: Item descriptions not displaying correctly

### ISSUE THREAD

**Issue by Brugosovi** [dwjclark11/TextRPG#4]
I think the line
`const std::wstring& item_desc = item->GetDescription();`
should be changed to
`const std::wstring& item_desc = data.at(index).get()->GetDescription();`
in the `RenderItem` function in _ItemMenuState.cpp_ (line 132). 

To the best of my understanding, `item->getDescription()` would return the description of **every** rendered item (for me it was displaying all item descriptions on top of each other), but `data.at(index).get()->GetDescription()` gives us **only** the description of the item the user is "hovering over." I know this isn't currently your active project, but nonetheless I hope this helps!

**Comment by dwjclark11** [comment]
@Brugoski Great catch. I will fix it with the following 
```c++
void ItemState::RenderItem(int x, int y, std::shared_ptr<Item> item)
{
	static int prevIndex = 0;

	int index = m_ItemSelector.GetIndex();
	const auto& data = m_ItemSelector.GetData();
	if (index >= data.size())
		return;

	const std::wstring& item_name = item->GetItemName();
	m_Console.Write(x, y, item_name);
	m_Console.Write(x + static_cast<int>(item_name.size() + 1), y, std::to_wstring(item->GetCount()));

	if (index != prevIndex)
	{
		// Clear the description area 
		m_Console.DrawPanelHorz(m_PanelBarX, 12, PANEL_BARS, BLUE, L" ");
		prevIndex = index;
	}

	const std::wstring& item_desc = data[index]->GetDescription();
	m_Console.Write(m_CenterScreenW - static_cast<int>(item_desc.size() / 2), 12, item_desc, LIGHT_BLUE);
}
```

Feel free to do a PR if you like, else I will fix this tomorrow. 

Thanks

**Comment by dwjclark11** [comment]
@Brugoski Actually I had time to make the fix. It should be good now see commit 4f24885. 

Thanks
